PRODUCTS_STAGE = [
    "/sugar-secret.html",
    "/gel-color-f01purewhite.html",
    "/pennello-trendy-super-fine.html",
    "/crystalpixie-candy-land.html",
    "/crystalpixie-deluxe-rush.html",
    "/crystalpixieedge-tropic-seafoam.html",
    "/gel-color-c42-fuxia-fuo.html",
    "/crystalpixie-classy-sassy.html",
    "/crystalpixie-comic-pop.html",
    "/gel-color-c42-fuxia-fuo.html",
]

PRODUCTS = [
    "/salviette-pads-hq-500-pz.html",
    "/dosatore-a-pompa.html",
    "/barattolo-vuoto-5-ml.html",
    "/vaschetta-per-miscelazione.html",
    "/pinzetta-obliqua.html",
    "/spazzolino-per-unghie.html",
    "/bastoncini-d-arancio-10-pz.html",
    "/nastro-proteggi-dita.html",
    "/pinza-stringivalli.html",
    "/fibra-di-vetro.html",
    "/aspiratore-nailduster.html",
    "/sacchetto-raccoglipolvere.html",
    "/taglia-tip.html",
    "/display-32-tip.html",
    "/gel-color-c1-chianti.html",
    "/gel-color-c2-ferrari.html",
    "/gel-color-c5-albicocca.html",
    "/gel-color-c7-nero-profondo.html",
    "/gel-color-c8-malibu.html",
    "/gel-color-c9-verde-petrolio.html",
]