PRODUCTS = [
    "/sugar-secret.html",
    "/gel-color-f01purewhite.html",
    "/pennello-trendy-super-fine.html",
    "/crystalpixie-candy-land.html",
    "/crystalpixie-deluxe-rush.html",
    "/crystalpixieedge-tropic-seafoam.html",
    "/gel-color-c42-fuxia-fuo.html",
    "/crystalpixie-classy-sassy.html",
    "/crystalpixie-comic-pop.html",
    "/gel-color-c42-fuxia-fuo.html",
]

PRODUCTS_PROD = [
    "/sugar-secret.html",
    "/gel-color-f01purewhite.html",
    "/pennello-trendy-super-fine.html",
    "/gel-semipermanente-per-unghie-sp14-virgin.html",
    "/crystalpixie-candy-land.html",
    "/crystalpixie-deluxe-rush.html",
    "/gel-color-c89-energia.html",
    "/crystalpixieedge-tropic-seafoam.html",
    "/gel-color-c42-fuxia-fuo.html",
    "/crystalpixie-classy-sassy.html",
    "/agenda-2019-giornaliera.html",
    "/crystalpixie-comic-pop.html",
    "/fresa-marathon-k35.html",
    "/contenitore-per-la-pulizia-degli-utensili.html",
    "/gel-color-c42-fuxia-fuo.html",
]