SEARCH_TERMS = [
    "smalto",
    "semipermanente",
    "accessori",
    "pennelli",
    "gel",
    "ricostruzione",
    "offerte",
    "glitter",
    "asparago",
    "fulmicotone",
    "nani da giardino",
    "dove comprare un divano",
    "supposte",
    "inseminazione artificiale",
]